name = "Chat Heads"
filename = "chat_heads-0.2.1+1.16.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3114/278/chat_heads-0.2.1+1.16.2.jar"
hash-format = "murmur2"
hash = "2710790699"

[update]
[update.curseforge]
file-id = 3114278
project-id = 407206
release-channel = "beta"
